### ISSUE TITLE
Multiline code

### ISSUE THREAD

**Issue by TanaTanoi** [TanaTanoi/messenger_formatter#1]
Currently it tries to support multiline code segments with backticks
Should be easy to disallow new lines with the regex, then maybe add one that _does_  support it

**Comment by TanaTanoi** [comment]
Kinda works at the moment, but a triple backtick like slack would be cool as well.

**Comment by pdonias** [comment]
Hi!

Shouldn't it just ignore triple backticks since Messenger now natively supports code blocks?
Right now, messenger_formatter just tries to format triple backticks as if they were single backticks.

This is what I type:
![capture du 2017-03-09 11-04-55](https://cloud.githubusercontent.com/assets/10992860/23745529/d41ce9fc-04b8-11e7-974f-96a82d392906.png)

This is what I get:
![capture du 2017-03-09 11-05-59](https://cloud.githubusercontent.com/assets/10992860/23745535/de384aa8-04b8-11e7-9668-7bd6c9a0d561.png)

And this is what I get after refreshing the page since the native formatting loads before messenger_formatter:
![capture du 2017-03-09 11-06-23](https://cloud.githubusercontent.com/assets/10992860/23745553/ea8c2f0e-04b8-11e7-90b4-358c4fb82de8.png)

Thanks!

**Comment by TanaTanoi** [comment]
Hey @pdonias!
Thanks for bringing that up! I'm going to look into it, but for now you can disable the code tag in the options. 
<img width="201" alt="screen shot 2017-03-14 at 3 51 39 pm" src="https://cloud.githubusercontent.com/assets/12075655/23883783/20c39bb6-08ce-11e7-9f67-ef285dfa1fd5.png">
Cheers

**Comment by pdonias** [comment]
Oh right! Thanks!

**Comment by pdonias** [comment]
But I still want to keep the inline code formatting so I'll just keep it enabled :)

**Comment by TanaTanoi** [comment]
Publishing the fix now, let me know if there's any other issues!

**Comment by pdonias** [comment]
@TanaTanoi It seems to work fine, thanks!

**Comment by pdonias** [comment]
However, it doesn't ignore triple backticks in Messenger's left panel:
![codeblock1](https://cloud.githubusercontent.com/assets/10992860/23942122/8b9d2450-096b-11e7-9cea-1c36a0f85d03.png)
and in the "new messages" tab:
![codeblock2](https://cloud.githubusercontent.com/assets/10992860/23942157/a04cae48-096b-11e7-9b48-8e2a30460335.png)
probably because Facebook removes line feeds when showing those previews.

**Comment by pdonias** [comment]
Also, this:
![capture du 2017-03-16 17-25-17](https://cloud.githubusercontent.com/assets/10992860/24007405/bb73b8e8-0a6e-11e7-8350-027ec1c59689.png)
is formatted like this:
![capture du 2017-03-16 17-25-43](https://cloud.githubusercontent.com/assets/10992860/24007419/c8dab090-0a6e-11e7-8aaa-a6fc7ae31127.png)
probably because of the `?`

Note: it doesn't matter if the `?` is at the end of the string or not.

**Comment by TanaTanoi** [comment]
Thanks again @pdonias! Am fixing it now.

**Comment by TanaTanoi** [comment]
Hopefully this fixes it (again)! Will push it to the chrome store next time I'm available.
